### ISSUE TITLE
django mongodb error in docker

### ISSUE THREAD

**Issue by vishal-wiai** [nesdis/djongo#456]
When I'm trying to use djongo in a docker container I'm getting the following error:

`pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 5f38bfe85a3d549230972fcd, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>`

Can anyone help how do I fix this? Not sure if this is a djongo error or the mongodb container error. 

Here is my `docker-compose.yml` file

```yml
version: '3'

services:
    web:
        restart: always
        build: .
        command: python pestserve/manage.py runserver 0.0.0.0:8001
        links: 
            - mongodb
        volumes:
            - .:/pestserve
        environment:
            MONGODB_HOSTNAME: 'mongodb'
        ports:
            - "8001:8001"
        depends_on:
            - mongodb


    mongodb:
        image: mongo:latest
        volumes:
            - ./mongo_data:/data/db
        ports:
            - "27017:27017"

volumes:
    mongo_data:
```
